# Generated by Django 5.0.6 on 2024-06-08 20:44

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
                ('date', models.DateField(default=datetime.date.today)),
                ('priority', models.CharField(max_length=15)),
                ('category', models.CharField(max_length=20)),
                ('subtasks', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=20)),
                ('uniqueIndex', models.DecimalField(decimal_places=50, max_digits=50)),
                ('assignedContacts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
