# Generated by Django 5.0.6 on 2024-06-12 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskitem',
            name='uniqueIndex',
            field=models.CharField(max_length=50),
        ),
    ]
