# Generated by Django 5.0.6 on 2024-06-12 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_taskitem_uniqueindex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskitem',
            name='subtasks',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
