# Generated by Django 5.0.6 on 2024-06-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_taskitem_subtasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskitem',
            name='assignedContacts',
        ),
        migrations.AlterField(
            model_name='taskitem',
            name='subtasks',
            field=models.JSONField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='taskitem',
            name='assignedContacts',
            field=models.JSONField(default=None),
        ),
    ]
