# Generated by Django 5.0.6 on 2024-06-19 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_remove_taskitem_assignedcontacts_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AssignedContacts',
        ),
    ]
